### ISSUE TITLE
Invalid permission declaration

### ISSUE THREAD

**Issue by remcomokveld** [googlesamples/easygoogle#11]
Correct me if I am wrong, but i think using this library in production builds would give issues with the declaration of permissions. Since Android 5.0 it is not allowed to have two apps declare the same permission if they are signed with a different keystore. The installation of the app will fail.

**Comment by samtstern** [comment]
Huh that is a good point ... this library is very experimental so I had not considered that.

I think I can fix it by passing permission as a parameter.

**Comment by samtstern** [comment]
Just submitted a PR which I believe should make this work now, great catch!  Let me know if you think the fix is not enough.
