### ISSUE TITLE
Use new AppInvites.getInvitation method, remove old method

### ISSUE THREAD

**Issue by samtstern** [googlesamples/easygoogle#15]

**Comment by samtstern** [comment]
Additional information:
The App Invites API in Play Services 8.3 has a much simpler way to get invitations which removes the need for the broadcast receiver and most of the code.

This commit (by me, in another repo) demonstrates the diff:
https://github.com/googlesamples/google-services/commit/b68c2ca69533c6badc051952485c0a0c8a7bbe90

**Comment by Solen-Win** [comment]
Read and edits.

**Comment by samtstern** [comment]
Closing this issue, EasyGoogle is no longer under active development.
