### ISSUE TITLE
R.string.gcm_permission when not using GCM?

### ISSUE THREAD

**Issue by drinfernoo** [googlesamples/easygoogle#23]
I'm mainly wanting to use this library to implement Google+ Sign-in, but after setting everything up, it crashes saying I haven't declared R.string.gcm_permission. Why do I need to do this if I'm not using GCM?

**Comment by francescocervone** [comment]
I temporarily solved creating an empty string resource named "gcm_permission"

**Comment by drinfernoo** [comment]
What should the string be in order for it to work correctly?

**Comment by francescocervone** [comment]
If you use GCM you must follow this guide: https://github.com/googlesamples/easygoogle#cloud-messaging
Since I don't use GCM like you, creating an empty string.

**Comment by drinfernoo** [comment]
Ok cool :)

**Comment by samtstern** [comment]
Sounds like I am trying to initialize `R.string.gcm_permission` even when `enableMessaging()` has not been called, which is a bug.

I will fix this in the next release, but in the meantime the suggested workaround of using an empty string will work.

**Comment by samtstern** [comment]
I am closing this issue as EasyGoogle is no longer under active development and is being moved to the "Google Archive".  Thank you for taking the time to engage with this library and file the issue, your thoughts helped to improve our APIs.
